//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CattleFarmingAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cattle_Farming_ManagementEntities : DbContext
    {
        public Cattle_Farming_ManagementEntities()
            : base("name=Cattle_Farming_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cattle> Cattle { get; set; }
        public virtual DbSet<CattleSale> CattleSale { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Farm> Farm { get; set; }
        public virtual DbSet<FoodCalculate> FoodCalculate { get; set; }
        public virtual DbSet<FoodConsume> FoodConsume { get; set; }
        public virtual DbSet<FoodStock> FoodStock { get; set; }
        public virtual DbSet<InjectedVaccination> InjectedVaccination { get; set; }
        public virtual DbSet<MilkCollection> MilkCollection { get; set; }
        public virtual DbSet<MilkSale> MilkSale { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vaccination> Vaccination { get; set; }
        public virtual DbSet<Weight> Weight { get; set; }
    }
}
